# Generated by Django 4.1.2 on 2022-10-13 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_name_ar_alter_pokemon_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
            preserve_default=False,
        ),
    ]
