# Generated by Django 4.1.2 on 2022-10-13 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(350), django.core.validators.MinValueValidator(50)]),
        ),
    ]
